pool:  
   name: Default 
    
trigger: 
  - main

steps: 
 - task: UseDotNet@2
   inputs:
     version: '6.x'
 - task: DotNetCoreCLI@2
   inputs:
    command: 'restore'
 - task: DotNetCoreCLI@2
   inputs:
    command: 'build'
   displayName: 'dotnet build'
 - task: DotNetCoreCLI@2
   inputs:
    command: test
    projects: '**/*Tests/*.csproj'
 - task: DotNetCoreCLI@2
   inputs:
     command: 'publish'
     publishWebProjects: true
 - task: AzureWebApp@1
   inputs:
     azureSubscription: 'Azure2'
     appType: 'webAppLinux'
     appName: 'ReverseApplication'
     package: '$(System.DefaultWorkingDirectory)/**/*.zip'    
 - script: echo Hello, world! 
   displayName: 'Run a one-line script'